/*
 * Buscar Processos no Porto Digital
 *
 * API criada para realizar requisições de processo.
 *
 * API version: 1.0.0
 * Contact: setinatende@tce.am.gov.br
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"database/sql"
	"encoding/json"
	"log"
	"net/http"
	"strconv"
)

func CadastraProcesso(w http.ResponseWriter, r *http.Request) {

	db, err := sql.Open("mysql", "root:@/spede")

	if err != nil {
		log.Fatal(err)
	}

	defer db.Close()

	tx, _ := db.Begin()

	stmt, err := tx.Prepare("INSERT INTO processo (id,numero,ano,natureza,especie,objeto,numeropaginas) values(?,?,?,?,?,?,?)")

	sid := r.Header.Get("id")
	id, _ := strconv.Atoi(sid)
	snumero := r.Header.Get("numero")
	numero, _ := strconv.Atoi(snumero)
	sano := r.Header.Get("ano")
	ano, _ := strconv.Atoi(sano)
	natureza := r.Header.Get("natureza")
	especie := r.Header.Get("especie")
	objeto := r.Header.Get("objeto")
	snumeropaginas := r.Header.Get("numeropaginas")
	numeropaginas, _ := strconv.Atoi(snumeropaginas)

	var p Processo
	p.Id = int64(id)
	p.Numero = int64(numero)
	p.Ano = int64(ano)
	p.Natureza = natureza
	p.Especie = especie
	p.Objeto = objeto
	p.NumeroPaginas = int64(numeropaginas)

	json, _ := json.Marshal(p)

	stmt.Exec(id, numero, ano, natureza, especie, objeto, numeropaginas)

	err = tx.Commit()

	if err != nil {
		log.Fatal(err)
		tx.Rollback()
	}

	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.Write(json)
	w.WriteHeader(http.StatusOK)
}
