/*
 * Buscar Processos no Porto Digital
 *
 * API criada para realizar requisições de processo.
 *
 * API version: 1.0.0
 * Contact: setinatende@tce.am.gov.br
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"database/sql"
	"encoding/json"
	"fmt"
	"log"
	"net/http"

	_ "github.com/go-sql-driver/mysql"
)

func BuscaSimples(w http.ResponseWriter, r *http.Request) {

	db, err := sql.Open("mysql", "root:@/spede")

	if err != nil {
		log.Fatal(err)
	}

	defer db.Close()

	rows, _ := db.Query("SELECT id,numero,ano,natureza,especie,objeto,numeropaginas FROM processo")

	defer rows.Close()

	var processo []Processo

	for rows.Next() {
		var p Processo
		rows.Scan(&p.Id, &p.Numero, &p.Ano, &p.Natureza, &p.Especie, &p.Objeto, &p.NumeroPaginas)
		processo = append(processo, p)
	}

	json, _ := json.Marshal(processo)

	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	fmt.Fprintf(w, string(json))
	w.WriteHeader(http.StatusOK)
}
