/*
 * Buscar Processos no Porto Digital
 *
 * API criada para realizar requisições de processo.
 *
 * API version: 1.0.0
 * Contact: setinatende@tce.am.gov.br
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Processo struct {
	Id int64 `json:"id,omitempty"`

	Numero int64 `json:"numero,omitempty"`

	Ano int64 `json:"ano,omitempty"`

	Natureza string `json:"natureza,omitempty"`

	Especie string `json:"especie,omitempty"`

	Objeto string `json:"objeto,omitempty"`

	NumeroPaginas int64 `json:"numero_paginas,omitempty"`
}
